baseurl = "http://asha-np.org/ja/"
languageCode = "ja-jp"
title = "ASHA Nepal Project"
contentdir = "content/ja"
publishdir = "public/ja"
canonifyUrls = true

[Params]
    hideServicesLink = true

[[Params.languages]]
    label = "English"
    url = "/../"

[[Params.social]]
    title = "facebook"
    icon = "facebook"
    url = "https://www.facebook.com/ashafusion/"
