baseurl = "http://asha-np.org/en/"
languageCode = "en-us"
title = "ASHA Nepal Project"
contentdir = "content/en"
publishdir = "public/en"
canonifyUrls = true

[Params]
    googleAnalytics = "UA-78099028-2"
    hideServicesLink = true

[[Params.languages]]
    label = "日本語"
    url = "/../"

[[Params.social]]
    title = "facebook"
    icon = "facebook"
    url = "https://www.facebook.com/ashafusion/"
